version: '3.8'

# env_file:
#   - path: ./.env.backend
#     required: true

services:
  database:
    image: mariadb
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}

  # backend:
  #   image: xedom/codeduel-be
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - 5000:5000
  #   environment:
  #     AUTH_GITHUB_CLIENT_CALLBACK_URL: ${AUTH_GITHUB_CLIENT_CALLBACK_URL}
  #     AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
  #     AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
  #     BINARY_NAME: ${BINARY_NAME}
  #     FRONTEND_URL: ${FRONTEND_URL}
  #     FRONTEND_URL_AUTH_CALLBACK: ${FRONTEND_URL_AUTH_CALLBACK}
  #     HOST: ${HOST}
  #     MARIADB_DATABASE: ${MARIADB_DATABASE}
  #     MARIADB_HOST: ${MARIADB_HOST}
  #     MARIADB_PASSWORD: ${MARIADB_PASSWORD}
  #     MARIADB_PORT: ${MARIADB_PORT}
  #     MARIADB_USER: ${MARIADB_USER}
  #     PORT: ${PORT}
  #   depends_on:
  #     - database

  lobby:
    image: xedom/codeduel-lobby
    container_name: codeduel-lobby
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5010:5010
    environment:
      HOST: 0.0.0.0
      PORT: 5010
      BACKEND_URL: http://localhost:5000
      BACKEND_API_KEY: xxxxxxxxxxxxxxxx
      RUNNER_URL: http://codeduel-runner:5020
      RUNNER_API_KEY: xxxxxxxxxxxxxxxx
    depends_on:
      - database

  runner:
    image: codeduel-runner
    container_name: codeduel-runner
    restart: always
    privileged: true
    ports:
      - 5020:5020
    environment:
      HOST: 0.0.0.0
      PORT: 5020
      FRONTEND_URL: "*"
      DOCKER_IMAGE_PREFIX: cd-runner-
      DOCKER_TIMEOUT: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - database

  # frontend:
  #   # image: xedom/codeduel-fe
  #   container_name: frontend
  #   profiles: ['prod']
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     BACKEND_URL: http://backend:5000
  #   depends_on:
  #     - backend
